spring:
  application:
    name: gateway-man

server:
  port: 8888


rpcman:
  #providers: http://localhost:8080,http://localhost:8081,http://localhost:8082
  zk:
    enabled: false
    zkServer: localhost:2181
    zkRoot: rpcman


# registry-man @linkUrl: https://github.com/ipipman/registry-man
registry-ipman:
  enabled: true
  servers: http://localhost:8484


logging:
  level:
    root: error
    cn.ipman.gateway: debug
    cn.ipman.rpc: debug
