spring:
  application:
    name: gateway-demo

server:
  port: 8889

rpcman:
  #providers: http://localhost:8080,http://localhost:8081,http://localhost:8082
  zk:
    enabled: true
    zkServer: localhost:2181
    zkRoot: rpcman

logging:
  level:
    root: error
    cn.ipman.gateway: debug
    cn.ipman.rpc: debug