### GET hello world
GET  http://localhost:8888/hello

### GET gateway
GET  http://localhost:8888/gw


### POST user
POST http://localhost:8888/gw/cn.ipman.rpc.demo.api.UserService
Content-Type: application/json

{
  "service": "cn.ipman.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}