### GET hello world
GET  http://localhost:8888/hello

### POST gateway rpcman
POST http://localhost:8888/gw/rpcman/cn.ipman.rpc.demo.api.UserService
Content-Type: application/json

{
  "service": "cn.ipman.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}


### POST gateway direct
POST http://localhost:8888/gw/direct?backend=http://192.168.31.232:9081/rpcman
Content-Type: application/json

{
  "service": "cn.ipman.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}


### POST gateway demo
POST http://localhost:8889/rpcman
Content-Type: application/json

{
  "service": "cn.ipman.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}